Otzar HaSefarim/Models/BookModel.cs
using System.ComponentModel.DataAnnotations;

namespace Otzar_HaSefarim.Models
{
	public class BookModel
	{
		public long Id { get; set; }
		[Required, StringLength(50)]
		public required string Name { get; set; }
		[Required]
		public required string Genre { get; set; }
		[Required]
		public required double Height { get; set; }
		[Required]
		public required double Width { get; set; }
		public long SetId { get; set; }
		public SetModel Set { get; set; }
	}
}

Otzar HaSefarim/Models/ErrorViewModel.cs
namespace Otzar_HaSefarim.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Otzar HaSefarim/Models/LibraryModel.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace Otzar_HaSefarim.Models
{
	[Index(nameof(Genre), IsUnique = true)]
	public class LibraryModel
	{
		public long Id { get; set; }
		[Required]
		public required string Genre { get; set; }
		public List<ShelfModel> Shelves { get; set; } = [];
	}
}

Otzar HaSefarim/Models/SetModel.cs
using System.ComponentModel.DataAnnotations;

namespace Otzar_HaSefarim.Models
{
	public class SetModel
	{
		public long Id { get; set; }
		[Required]
		public required string Title { get; set; }
		public long ShelfId { get; set; }
		public ShelfModel Shelf { get; set; }
		public List<BookModel> Books { get; set; } = [];
	}
}

Otzar HaSefarim/Models/ShelfModel.cs
using System.ComponentModel.DataAnnotations;

namespace Otzar_HaSefarim.Models
{
	public class ShelfModel
	{
		public long Id { get; set; }
		[Required]
		public required double Height { get; set; }
		[Required]
		public required double Width { get; set; }
		public long LibraryId { get; set; }
		public LibraryModel Library { get; set; }
		public List<SetModel> Sets { get; set; } = [];

	}
}

Otzar HaSefarim/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using Otzar_HaSefarim.Service;
using Otzar_HaSefarim.ViewModel;

namespace Otzar_HaSefarim.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookService _bookService;

        public BookController(IBookService bookService)
        {
            _bookService = bookService;
        }


        public IActionResult Index(long id)
        {
            ViewBag.SetId = id;
            return View(_bookService.GetAllBooksById(id));
        }

        public IActionResult Create(long SetId)
        {
            ViewBag.SetId = SetId;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(BookVM bookVM, long SetId)
        {
            if (bookVM == null)
            {
                return View("Index");
            }
            _bookService.AddBook(bookVM, SetId);
            return RedirectToAction("Index", new { id = SetId });
        }
    }
}

Otzar HaSefarim/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Otzar_HaSefarim.Data;
using Otzar_HaSefarim.Models;
using System.Diagnostics;

namespace Otzar_HaSefarim.Controllers
{
	public class HomeController : Controller
	{
		private readonly ApplicationDbContext _context;

		public HomeController(ApplicationDbContext context)
		{
			_context = context;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Otzar HaSefarim/Controllers/LibraryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Otzar_HaSefarim.Data;
using Otzar_HaSefarim.Models;
using Otzar_HaSefarim.Service;
using Otzar_HaSefarim.ViewModel;
namespace Otzar_HaSefarim.Controllers
{
	public class LibraryController : Controller
	{
		private readonly ILibraryService _libraryService;

        public LibraryController(ILibraryService libraryService)
        {
            _libraryService  = libraryService;
        }

		public async Task<IActionResult> Index() =>
			View(await _libraryService.GetAllLibraries());

		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create(LibraryVM libraryVM)
		{
			if (libraryVM == null)
			{
				return View("Index");
			}
			_libraryService.AddGenre(libraryVM);
			return RedirectToAction("Index");
		}

        public IActionResult Shelves(long Id)
        {
			var shelvesLibrary = _libraryService.GetLibraryShelves(Id);
			return View(shelvesLibrary);
        }
    }
}

Otzar HaSefarim/Controllers/SetController.cs
using Microsoft.AspNetCore.Mvc;
using Otzar_HaSefarim.Service;
using Otzar_HaSefarim.ViewModel;

namespace Otzar_HaSefarim.Controllers
{
    public class SetController : Controller
    {
        private readonly ISetService _setService;

        public SetController(ISetService setService)
        {
            _setService = setService;
        }


        public IActionResult Index(long id)
        {
            ViewBag.ShelfId = id;
            return View(_setService.GetAllSetsById(id));
        }

        public IActionResult Create(long ShelfId)
        {
            ViewBag.ShelfId = ShelfId;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(SetVM setVM, long ShelfId)
        {
            if (setVM == null)
            {
                return View("Index");
            }
            _setService.CreateSet(setVM, ShelfId);
            return RedirectToAction("Index", new { id = ShelfId });
        }
    }
}

Otzar HaSefarim/Controllers/ShelfController.cs
using Microsoft.AspNetCore.Mvc;
using Otzar_HaSefarim.Service;
using Otzar_HaSefarim.ViewModel;

namespace Otzar_HaSefarim.Controllers
{
    public class ShelfController : Controller
    {
        private readonly IShelfService _shelfService;

        public ShelfController(IShelfService shelfService)
        {
            _shelfService = shelfService;
        }


        public IActionResult Index(long id)
        {
           ViewBag.LibraryId = id;
           return View(_shelfService.GetAllShelvesById(id));
        }

        public IActionResult Create(long LibraryId)
        {
            ViewBag.libraryId = LibraryId;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ShelfVM shelfVM, long LibraryId)
        {
            if (shelfVM == null)
            {
                return View("Index");
            }
            _shelfService.CreateShelf(shelfVM, LibraryId);
            return RedirectToAction("Index", new {id = LibraryId});
        }
    }
}

Otzar HaSefarim/Views/Book/Create.cshtml
@model Otzar_HaSefarim.ViewModel.BookVM

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>
<h3>@ViewBag.SetfId</h3>
<h4>BookVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Height" class="control-label"></label>
                <input asp-for="Height" class="form-control" />
                <span asp-validation-for="Height" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Width" class="control-label"></label>
                <input asp-for="Width" class="form-control" />
                <span asp-validation-for="Width" class="text-danger"></span>
            </div>
            <div class="form-group">
                
                <input asp-for="SetId" value="@ViewBag.SetId" class="form-control" hidden/>
                
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Otzar HaSefarim/Views/Book/Index.cshtml
@model IEnumerable<Otzar_HaSefarim.Models.BookModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<h2>@ViewBag.SetfId</h2>
<p>
    @Html.ActionLink("Create New", "Create", "Book", new { SetId = ViewBag.SetId })
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Height)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Width)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SetId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Height)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Width)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SetId)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

Otzar HaSefarim/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Otzar HaSefarim/Views/Library/Create.cshtml
@model Otzar_HaSefarim.ViewModel.LibraryVM;

<form asp-action="Create" method="post">
	@Html.AntiForgeryToken
	<label for="fname">AddGenre</label>
	<input asp-for="Genre" type="text" value="@Model">
	<button type="submit" value="save">Add Genre</button>
</form>

Otzar HaSefarim/Views/Library/Index.cshtml
@model IEnumerable<Otzar_HaSefarim.Models.LibraryModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<h3>Library</h3>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genre)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                @Html.ActionLink("Shelves", "Index", "Shelf", new { id = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

Otzar HaSefarim/Views/Set/Create.cshtml
@model Otzar_HaSefarim.ViewModel.SetVM

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>
<h3>@ViewBag.ShelfId</h3>
<h4>SetVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                
                <input name="ShelfId" value="@ViewBag.ShelfId" class="form-control" hidden />
                
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Otzar HaSefarim/Views/Set/Index.cshtml
@model IEnumerable<Otzar_HaSefarim.Models.SetModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<h2>@ViewBag.ShelfId</h2>
<p>
    @Html.ActionLink("Create New", "Create", "Set", new { ShelfId = ViewBag.ShelfId })
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ShelfId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShelfId)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                @Html.ActionLink("Books", "Index", "Book", new { id = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

Otzar HaSefarim/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Otzar_HaSefarim</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Otzar_HaSefarim.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Otzar_HaSefarim</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Library" asp-action="Index">Library</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Otzar_HaSefarim - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Otzar HaSefarim/Views/Shelf/Create.cshtml
@model Otzar_HaSefarim.ViewModel.ShelfVM

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>
<h3>LibraryId is @ViewBag.LibraryId</h3>
<h4>ShelfVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Height" class="control-label"></label>
                <input asp-for="Height" class="form-control" />
                <span asp-validation-for="Height" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Width" class="control-label"></label>
                <input asp-for="Width" class="form-control" />
                <span asp-validation-for="Width" class="text-danger"></span>
            </div>
            <div class="form-group", hidden>
                <input name="LibraryId" value="@ViewBag.LibraryId" class="form-control" hidden />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Otzar HaSefarim/Views/Shelf/Index.cshtml
@model IEnumerable<Otzar_HaSefarim.Models.ShelfModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<h3>Shelf</h3>
<h3>@ViewBag.LibraryId</h3>
<p>
    @Html.ActionLink("Create New Shelf", "Create", "Shelf", new { LibraryId = ViewBag.LibraryId })
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Height)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Width)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LibraryId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Height)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Width)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LibraryId)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                @Html.ActionLink("Sets", "Index", "Set", new { id = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>